{{- range .Values.ingresscontrollers }}
{{ if eq ( .enabled | toString) "true" }}
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: {{ .name }}
  namespace: openshift-ingress-operator
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .replicas | default "2" }}
  {{- if .defaultCertificate }}
  defaultCertificate:
    name: {{ .defaultCertificate }}
  {{- end }}
  {{- if .domain }}
  domain: {{ .domain }}
  {{- end }}
  {{- if .routeAdmission }}
  routeAdmission:
    {{- if .routeAdmission.namespaceOwnership }}
    namespaceOwnership: {{ .routeAdmission.namespaceOwnership }}
    {{- end }}
    {{- if .routeAdmission.namespaceSelector }}
    {{- end }}
    {{- if .routeAdmission.wildcardPolicy }}
    wildcardPolicy: {{ .routeAdmission.wildcardPolicy }}
    {{- end }}
  {{- end}}

  {{- if .endpointPublishingStrategy }}
  endpointPublishingStrategy:
    type: {{ .endpointPublishingStrategy.type | default "HostNetwork" }}
    {{- if .endpointPublishingStrategy.hostNetwork }}
    hostNetwork:
      httpPort: {{ .endpointPublishingStrategy.hostNetwork.httpPort }}
      httpsPort: {{ .endpointPublishingStrategy.hostNetwork.httpsPort }}
      statsPort: {{ .endpointPublishingStrategy.hostNetwork.statsPort }}
    {{- end }}
  {{- end }}
  {{- if .tlsSecurityProfile }}
  tlsSecurityProfile: 
    {{- toYaml .tlsSecurityProfile | nindent 4 }}
  {{- end }}
  {{- if .namespaceSelector }}
  namespaceSelector:
    matchExpressions:
      {{- range .namespaceSelector.matchExpressions }}
      {{- include "tpl.matchExpressions" . }}
      {{- end }}
  {{- end }}

  {{- if .nodePlacement }}
  {{- with .nodePlacement }}
  nodePlacement:
    {{- if .nodeSelector }}
    nodeSelector:
      matchLabels: 
        {{ .nodeSelector.key }}: {{ .nodeSelector.value | quote }}
    {{- end }}

  {{- if .tolerations }}
{{ include "tpl.tolerations" .tolerations | indent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}

{{- end }}
{{- end }}