{{ if .Values.monitoring }}
{{ if eq ( .Values.monitoring.enabled | toString) "true" }}
{{- with .Values.monitoring }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
data:
  config.yaml: |

    {{- /* ALERTMANAGER CONFIGURATION */}}
    {{- with .alertmanagerMain }}  
    alertmanagerMain:
      {{- if .disable_local_alertmanager }}
      {{- if or ( eq (.disable_local_alertmanager | toString) "true") (eq (.disable_local_alertmanager | toString) "false") }}
      enabled: {{.disable_local_alertmanager }}
      {{- end }}
      {{- end }}

      {{- if .secrets }}
      secrets:
        {{- range .secrets }}
        - {{.}}
        {{- end }}
      {{- end }}

      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
{{ include "tpl.tolerations.override" .tolerations | indent 6 }}
      {{- end }}

      {{- if .storage }}
      volumeClaimTemplate:
        metadata: {}
        spec:
          resources:
            requests:
              storage: {{ .storage.size | default "40Gi" }}
      {{- end }}
          storageClassName: {{ .storage.class | default "gp2-csi" }}
        status: {}
    
      {{- if .resources }}
{{ include "tpl.resources" .resources | indent 6 }}
      {{- end }}
    {{- end }}
    enableUserWorkload: {{ ( .enableUserWorkload | toString) | default "false" }}
    {{- /* KUBE STATE METRIC CONFIGURATION */}}
    {{- with .kubeStateMetrics }}
    kubeStateMetrics:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
{{ include "tpl.tolerations.override" .tolerations | indent 6 }}
      {{- end }}

      {{- if .resources }}
{{ include "tpl.resources" .resources | indent 6 }}
      {{- end }}
    {{- end }}


    {{- /* METRICS SERVER CONFIGURATION */}}
    {{- with .metricsServer }}
    metricsServer:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
{{ include "tpl.tolerations.override" .tolerations | indent 6 }}
      {{- end }}

      {{- if .resources }}
{{ include "tpl.resources" .resources | indent 6 }}
      {{- end }}
    {{- end }}    

    {{- /* MONITORING PLUGIN CONFIGURATION */}}
    {{- with .monitoringPlugin }}
    monitoringPlugin:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
{{ include "tpl.tolerations.override" .tolerations | indent 6 }}
      {{- end }}

      {{- if .resources }}
{{ include "tpl.resources" .resources | indent 6 }}
      {{- end }}
    {{- end }}

    {{- /* NODEEXPORTER CONFIGURATION */}}
    {{- with .nodeExporter }}
    nodeExporter:
{{ include "tpl.nodeExporter.collectors" .collectors | indent 6  }}
      {{- if .resources }}
{{ include "tpl.resources" .resources | indent 6 }}
      {{- end }}
    {{- end }}

    {{- /* OPENSHIFT STATE METRIC CONFIGURATION */}}
    {{- with .openshiftStateMetrics }}
    openshiftStateMetrics:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
{{ include "tpl.tolerations.override" .tolerations | indent 6 }}
      {{- end }}

      {{- if .resources }}
{{ include "tpl.resources" .resources | indent 6 }}
      {{- end }}
    {{- end }}

    {{- /* PROMETHEUS CONFIGURATION */}}
    {{- with .prometheusK8s }}
    prometheusK8s:
      {{- if .additionalAlertmanagerConfigs }}
      additionalAlertmanagerConfigs:
        {{- toYaml .additionalAlertmanagerConfigs | nindent 6 }}
      {{- end }}
      collectionProfile: {{ .collectionProfile | default "full" }}
      {{- if .externalLabels }}
      externalLabels:
        {{- toYaml .externalLabels | nindent 8 }}
      {{- end }}
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}
      retention: {{ .retention | default "15d" }}
      {{- if .tolerations }}
{{ include "tpl.tolerations.override" .tolerations | indent 6 }}
      {{- end }}
      {{- if eq (.retentionSize | toString) "0"}}
      {{- else }}
      retentionSize: {{ .retentionSize }}
      {{- end }}

      {{- if .storage }}
      volumeClaimTemplate:
        metadata: {}
        spec:
          resources:
            requests:
              storage: {{ .storage.size | default "100Gi" }}
          storageClassName: {{ .storage.class | default "gp2-csi" }}
        status: {}
      {{- end }}

      {{- if .resources }}
{{ include "tpl.resources" .resources | indent 6 }}
      {{- end }}
    {{- end }}

    {{- with .prometheusOperator }}
    prometheusOperator:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
{{ include "tpl.tolerations.override" .tolerations | indent 6 }}
      {{- end }}

      {{- if .resources }}
{{ include "tpl.resources" .resources | indent 6 }}
      {{- end }}
    {{- end }}

    {{- /* TELEMETER CLIENT CONFIGURATION */}}
    {{- with .telemeterClient }}
    telemeterClient:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
{{ include "tpl.tolerations.override" .tolerations | indent 6 }}
      {{- end }}

      {{- if .resources }}
{{ include "tpl.resources" .resources | indent 6 }}
      {{- end }}
    {{- end }}

    {{- /* THANOS QUERIER CONFIGURATION */}}
    {{- with .thanosQuerier }}
    thanosQuerier:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .tolerations }}
{{ include "tpl.tolerations.override" .tolerations | indent 6 }}
      {{- end }}

      {{- if .resources }}
{{ include "tpl.resources" .resources | indent 6 }}
      {{- end }}
    {{- end }}

{{- end }}
{{- end }}
{{- end }}