---
apiVersion: v2
name: network-observability
description: Installs and configures OpenShift Network Observability.
version: 1.0.12
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/network-observability
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/netobserv-icon.png
dependencies:
  - name: helper-loki-bucket-secret
    version: ~1.0.0
    repository: https://charts.stderr.at/
    condition: helper-loki-bucket-secret.enabled
  - name: helper-operator
    version: ~1.0.0
    repository: https://charts.stderr.at/
#  - name: helper-status-checker
#    version: ~4.0.0
#    repository: https://charts.stderr.at/
  - name: helper-objectstore
    version: ~1.0.0
    repository: https://charts.stderr.at/
    condition: helper-objectstore.enabled
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - security
  - network
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: Initial Release
    - kind: fixed
      description: fixing icon
    - kind: added
      description: added README and did some cleanup
    - kind: added
      description: added tpl chart
