{{- if eq ( .Values.netobserv.enabled | toString) "true" }}
{{- with .Values.netobserv }}
---
apiVersion: flows.netobserv.io/v1beta1
kind: FlowCollector
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "10" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
spec:
  namespace: {{ .namespace.name }}
  agent:
    ebpf:
      logLevel: info
      cacheMaxFlows: 100000
      resources:
        limits:
          memory: 800Mi
        requests:
          cpu: 100m
          memory: 50Mi
      sampling: 50
      imagePullPolicy: IfNotPresent
      excludeInterfaces:
        - lo
      kafkaBatchSize: 10485760
      cacheActiveTimeout: 5s
      interfaces: []
    type: EBPF
  consolePlugin:
    logLevel: info
    enable: true
    portNaming:
      enable: true
      portNames:
        '3100': loki
    quickFilters:
      - default: true
        filter:
          dst_namespace!: 'openshift-,netobserv'
          src_namespace!: 'openshift-,netobserv'
        name: Applications
      - filter:
          dst_namespace: 'openshift-,netobserv'
          src_namespace: 'openshift-,netobserv'
        name: Infrastructure
      - default: true
        filter:
          dst_kind: Pod
          src_kind: Pod
        name: Pods network
      - filter:
          dst_kind: Service
        name: Services network
    imagePullPolicy: IfNotPresent
    autoscaler:
      maxReplicas: 3
      metrics:
        - resource:
            target:
              averageUtilization: 50
              type: Utilization
            name: cpu
          type: Resource
      minReplicas: 1
      status: DISABLED
    replicas: 1
  deploymentModel: DIRECT
  exporters: []
  loki:
    timeout: 10s
    enable: true
    tenantID: netobserv
    statusTls:
      caCert:
        certFile: service-ca.crt
        name: {{ .lokistack_name }}-ca-bundle
        type: configmap
      enable: true
      insecureSkipVerify: true
    url: 'https://{{ .lokistack_name }}-gateway-http.openshift-netobserv-operator.svc:8080/api/logs/v1/network'
    batchWait: 1s
    authToken: FORWARD
    tls:
      caCert:
        certFile: service-ca.crt
        name: {{ .lokistack_name }}-gateway-ca-bundle
        type: configmap
      enable: true
      insecureSkipVerify: true
    batchSize: 10485760
    statusUrl: 'https://{{ .lokistack_name }}-distributor-http.openshift-netobserv-operator.svc:3100/'
  processor:
    logLevel: info
    metrics:
      disableAlerts: []
      server:
        port: 9102
        tls:
          type: DISABLED
    resources:
      limits:
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 100Mi
    kafkaConsumerQueueCapacity: 1000
    imagePullPolicy: IfNotPresent
    logTypes: FLOWS
    kafkaConsumerReplicas: 3
    kafkaConsumerBatchSize: 10485760
{{- end }}
{{- end }}