{{- if eq (.Values.enabled | toString) "true" }}
{{- if .Values.serviceAccount }}
{{- if eq (.Values.serviceAccount.create | toString) "true" }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount.name | default "acs-backup" }}
  namespace: stackrox
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
