{{- with .Values.loggingConfig }}
{{- if or (eq ( .operatorVersion | toString) "6.0") (eq ( .operatorVersion | toString) "6") (eq ( .operatorVersion | toString) "6.x") }}
{{- if eq ( .enabled | toString) "true" }}
{{- if .collectorServiceAccount.bindings }}
{{- range .collectorServiceAccount.bindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ . }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.loggingConfig.collectorServiceAccount.name | default "cluster-logging-operator" }}
    namespace: openshift-logging
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
