{{- with .Values.certManager }}
{{ if eq (.enable_patch | toString) "true" }}
---
apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  name: cluster
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 10 | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  logLevel: {{ .logLevel | default "Normal" }}
  operatorLogLevel: {{ .operatorLogLevel | default "Normal" }}
  managementState: Managed
  observedConfig: null
  controllerConfig:
    {{ if eq (.overrideArgs.enabled | toString) "true" }}
    overrideArgs:
      {{- range .overrideArgs.args }}
      - {{ . }}
      {{- end }}
    {{- end }}
  {{- if .unsupportedConfigOverrides }}
  unsupportedConfigOverrides:
{{- toYaml .unsupportedConfigOverrides | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}