name: Lint and Test Charts

on: 
  push:
    branches: 
      - main
    paths:
      - 'charts/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.13.5

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            # echo "::set-output name=changed::true"
            echo name=changed::true" >> $GITHUB_OUTPUT
          else
            # echo "::set-output name=changed::false"
            echo name=changed::false" >> $GITHUB_OUTPUT
          fi
   
        # you MUST increase the version of the chart, otherwise chart-releaser will fail
      - name: Run chart-testing (lint)
        run: |
          #if [ "${{ steps.list-changed.outputs.changed }}" = true ]; then
          #  echo "checking changed charts only"
            ct lint --debug --target-branch ${{ github.event.repository.default_branch }}
          #else
          #  echo "checking ALL charts"
          #  ct lint --all --debug --target-branch ${{ github.event.repository.default_branch }}
          #fi
